version: '3'

services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USR}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
